[phases.setup]
nixPkgs = ['nodejs-18_x', 'openssl', 'openssl_1_1']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['PRISMA_CLI_BINARY_TARGETS=debian-openssl-1.1.x npm run build']

[start]
cmd = 'npx prisma migrate deploy && npm run start'

[variables]
PRISMA_CLI_BINARY_TARGETS = 'debian-openssl-1.1.x'
